server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  include /etc/nginx/mime.types;

  gzip on;
  gzip_types text/css application/javascript image/svg+xml font/ttf;

  location = /backend/contact-us.php {
    default_type application/json;
    add_header Cache-Control "no-store";
    return 200 '{"status":"success","delivered":false,"message":"Thank you for reaching out. We will connect with you at the earliest."}';
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
